Repository f-lab-edu/danggeun, pull requests merged in 2023-11, with the labels that each got.

#48 Feature/#9 user join
  provision/http/Location.http
  provision/http/Mail.http
  provision/http/User.http
  provision/http/http-client.env.json
  src/main/java/com/danggeun/commons/advice/ExceptionAdvice.java
  src/main/java/com/danggeun/commons/config/RestTemplateConfig.java
  src/main/java/com/danggeun/commons/config/SecurityConfig.java
  src/main/java/com/danggeun/commons/util/EmailRedisService.java
  src/main/java/com/danggeun/commons/util/RandomNumber.java
  src/main/java/com/danggeun/mail/controller/MailController.java
  src/main/java/com/danggeun/mail/dto/MailDTO.java
  src/main/java/com/danggeun/mail/exception/CertificationNumberMismatchException.java
  src/main/java/com/danggeun/mail/exception/EmailCertificationNumberSendException.java
  src/main/java/com/danggeun/mail/exception/EmailDuplicatedException.java
  src/main/java/com/danggeun/mail/exception/EmailFormatException.java
  src/main/java/com/danggeun/mail/exception/EmailInvalidRequestException.java
  src/main/java/com/danggeun/mail/exception/NoCertificationException.java
  src/main/java/com/danggeun/mail/service/MailService.java
  src/main/java/com/danggeun/region/controller/RegionController.java
  src/main/java/com/danggeun/region/dto/Address.java
  src/main/java/com/danggeun/region/dto/Documents.java
  src/main/java/com/danggeun/region/dto/LocationAdressResponse.java
  src/main/java/com/danggeun/region/dto/RegionDTO.java
  src/main/java/com/danggeun/region/exception/AddressSearchKakaoApiException.java
  src/main/java/com/danggeun/region/repository/JdbcTemplateRegionRepository.java
  src/main/java/com/danggeun/region/repository/RegionRepository.java
  src/main/java/com/danggeun/region/service/RegionService.java
  src/main/java/com/danggeun/user/controller/UserController.java
  src/main/java/com/danggeun/user/dto/UserDTO.java
  src/main/java/com/danggeun/user/enumerate/LoginType.java
  src/main/java/com/danggeun/user/exception/NicknameDuplicatedException.java
  src/main/java/com/danggeun/user/exception/UserIncorrectResultSizeException.java
  src/main/java/com/danggeun/user/exception/UserInvalidRequestException.java
  src/main/java/com/danggeun/user/exception/UserPasswordFormatException.java
  src/main/java/com/danggeun/user/repository/JdbcTemplateUserRepository.java
  src/main/java/com/danggeun/user/repository/UserRepository.java
  src/main/java/com/danggeun/user/service/UserService.java
  src/test/java/com/danggeun/commons/util/EmailRedisServiceTest.java
  src/test/java/com/danggeun/region/service/RegionServiceTest.java
  src/test/java/com/danggeun/user/service/UserServiceTest.java
Labels: 회원가입

#62 feature/#13-article-write
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/danggeun/annotation/SpringIntegrationTest.java
  src/test/java/com/danggeun/article/ArticleTest.java
  src/test/java/com/danggeun/comment/CommentTest.java
Labels: 게시글

#52 Feature/#50 jpa init
  build.gradle
  src/main/java/com/danggeun/DanggeunApplication.java
  src/main/java/com/danggeun/commons/config/AuditingConfig.java
  src/main/java/com/danggeun/commons/entity/BaseEntity.java
  src/main/java/com/danggeun/commons/entity/BaseTimeEntity.java
  src/main/resources/application-local.yml
Labels: Auditing

#56 Feature#54 code coverage
  .github/workflows/gradle.yml
  .gitmessage.txt
  build.gradle
Labels: Server
